server:
  port: 8085

spring:
  cloud:
    stream:
      bindings:
        output_channel:
          destination: output
          binder: local_rabbit
          group: city
      binders:
        local_rabbit:
          type: rabbit
          environment:
            spring:
              rabbitmq:
                host: localhost
                port: 5672
                username: guest
                password: guest